name             'apache'
maintainer       'Andrew Redmond'
maintainer_email 'andrewpredmond@gmail.com'
slicense          'MIT'
description      'Installs/Configures apache'
long_description 'Installs/Configures apache'
version          '0.1.0'
